### ISSUE TITLE
[Feature request] option to include border in the measurement

### ISSUE THREAD

**Issue by Andarist** [nkbt/react-height#20]
Just like in the title. I could provide PR for this if you find this useful

**Comment by nkbt** [comment]
Hi @Andarist 
I decided not to go this way from the beginning, since it also means supporting margins and all sorts of other css things. I suggest just to wrap element with borders/margins into a plain one that will be measured instead.

Just writing this I realized that alternatively we could accept an optional callback that can pick any element values and if not provided use default like:

```js
getElementHeight(element) {
  return element.clientHeight;
}
```

So if you wish to include borders or margins - or anything else - you will be able to do so easily.

**Comment by Andarist** [comment]
Yeah, that's probably a reasonable default with provided ability to calculate the height as the user wish, so the lib doesnt have to worry about about all of this, and not even consider `box-sizing` etc.

I might make a PR for this 2morrow, should I proceed with this?

**Comment by nkbt** [comment]
Would be fantastic!
