### ISSUE TITLE
Height not updating when content inside container changes?

### ISSUE THREAD

**Issue by KingScooty** [nkbt/react-height#9]
I've noticed that the height doesn't seem to be updating when the content inside the container changes. The height just stays the same after the initial render. Is there anyway i can get it to re-measure the height?

I have some dumb components that receive json and render out to the view. I want to be able to track the height of the containers of each of the items, but when changing the route and the json response, the height does not update on the containers, it just stays as the original value :/ I have to physically refresh the page for the heights to update to the new values.

What is the dirty param used for? (it doesn't seem to fix my issue)

**Comment by KingScooty** [comment]
Is there a way to trigger ReactHeight to re-measure the height when props change?

**Comment by nkbt** [comment]
Yeah, pass "dirty" prop to recalc height. See example for reference (and it
should be in readme)

That is intentional. For speed. I have another one that recalcs all the
time react-element-resize, but would not recommend using it for more then
5-10 elements at a time. Not like perf is bad, but if you look at how it is
implemented, you will understand :)

**Comment by wmertens** [comment]
So if I understand correctly, you need to decide yourself when the height might be dirty and then toggle the dirty flag on ReactHeight?

**Comment by nkbt** [comment]
@wmertens  react height can recalc height when children has changed or dirty flag is set, functionality is actually fairly limited. The reason it is done this way - performance. https://github.com/nkbt/react-element-resize does it constantly and has correct debounced height reported, though it does not fit perfectly when you want to have a table with 1000k collapsible rows.

Would be nice if collapse can use either of them depending on a preference... I'm goind to do something about it soon (hopefully)

**Comment by wmertens** [comment]
Yes, so that's what I don't understand, dirty is a boolean, but setting it
to true does not make it update continuously…

**Comment by nkbt** [comment]
Yeah, it is not a perfect solution =(. At the moment only fact of changing it from `false` to `true` counts, not the other way around. 

That is not a big deal for `react-collapse` since it removes `react-height` as soon as height is known. That was the main way to use this component. One time basically.

I don't think `react-height` is generic enough to serve as constant height measurer, and probably I should replace it with `react-element-resize`'s code instead, and keep this high-perf height measurement just as part of `react-collapse` component itself.

That would be more fair...
